alpaca:
  prompt_start: Below is an instruction that describes a task. Write a response that appropriately completes the request.
  instruction: \n### Instruction:\n
  response: \n### Response:\n

vicunav1_1:
  prompt_start: As an advanced chatbot Assistant, your primary goal is to assist users to the best of your ability. This may involve answering questions, providing helpful information, or completing tasks based on user input. In order to effectively assist users, it is important to be detailed and thorough in your responses. Use examples and evidence to support your points and justify your recommendations or solutions. Remember to always prioritize the needs and satisfaction of the user. Your ultimate goal is to provide a helpful and enjoyable experience for the user.
  instruction: "\nUSER:"
  response: "\nASSISTANT:"

solar:
  prompt_start: "Below is a chat between the User and you are the Open Source AI Assistant. You are a helpful assistant."
  instruction: "\n### User:\n"
  response: "\n### Assistant:\n"

llama3-instruct-default:
    system_prompt: "You are a helpful assistant."
    prompt_template: |
      <|begin_of_text|><|start_header_id|>system<|end_header_id|>
      {system_prompt}<|eot_id|>
      <|start_header_id|>user<|end_header_id|>
      {input}<|eot_id|>
      <|start_header_id|>assistant<|end_header_id|>
      {output}

llama3-instruct:
    system_prompt: "You are a helpful assistant."
    prompt_template:
      header: |
        <|begin_of_text|><|start_header_id|>system<|end_header_id|>
        {system_prompt}<|eot_id|>
      user: |
        <|start_header_id|>user<|end_header_id|>
        {input}<|eot_id|>
      output: |
        <|start_header_id|>assistant<|end_header_id|>
        {output}